name: Demo Pipeline
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Pipeline Runner
        uses: actions/checkout@v4
  
      - name: Cypress run
        uses: cypress-io/github-action@v6